---
abstract: 'a fast and reliable mailq-like utility for postfix'
author:
  - 'Cosimo Streppone <cosimo@opera.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.102400'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Postfix-Mailq
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Postfix-Mailq
  repository: git://github.com/cosimo/perl5-postfix-mailq.git
version: 0.01
